[package]
name = "myapi-rust"
version = "0.1.0"
authors = ["Marcel"]

[dependencies]
regex = "1.10.4"

[dev-dependencies]
pretty_assertions = "1.3.0"                         # nicer looking assertions

